### ISSUE TITLE
A issue 

### ISSUE THREAD

**Issue by imnagarajan** [sgkoishi/yaaiomni#1]
![Screenshot_20230104-164220](https://user-images.githubusercontent.com/107058543/210543139-59f31524-14e3-4911-801a-8a6ba8e078ac.png)

**Comment by imnagarajan** [comment]
> Hmmmm... Could you try run `ls -al` in `ServerPlugins`?

No

**Comment by imnagarajan** [comment]
> Hmmmm... Could you try run `ls -al` in `ServerPlugins`?

I just do is i put the all .dll in to server plugin folder

**Comment by sgkoishi** [comment]
Can you scroll up and down to show the full error message?

**Comment by imnagarajan** [comment]
> Can you scroll up and down to show the full error message?

If want i can send you the log file

**Comment by imnagarajan** [comment]
![Screenshot_20230105-144649](https://user-images.githubusercontent.com/107058543/210744794-18d4fe6e-4b1b-4716-a60c-11fecc24a853.png)
![Screenshot_20230105-144709](https://user-images.githubusercontent.com/107058543/210744810-4732a048-2d49-45d8-a141-6e44230ef05d.png)
![Screenshot_20230105-144714](https://user-images.githubusercontent.com/107058543/210744815-3d3a15e4-fcab-4d3a-a157-2e6d10506c92.png)

**Comment by imnagarajan** [comment]
I can't send the log so i send the screenshot @sgkoishi

**Comment by sgkoishi** [comment]
Somehow sounds like a question related to "how to use plugin". You need to run `chmod +r ServerPlugins/*`. If you don't know how, ask your provider (from the screenshot it's [skynode](https://www.skynode.pro/support)).

**Comment by sgkoishi** [comment]
See also: https://github.com/sgkoishi/yaaiomni#faq
