### ISSUE TITLE
An issue about player quit

### ISSUE THREAD

**Issue by TskimiSeiran** [sgkoishi/yaaiomni#4]
I use this plugin on my server,and i founded an issue.
When player quit server,theirs character still in server,but when their come back to server,the character haven't gone,means two same characters in server(one is ghost).
Plugin Version:v130

**Comment by TskimiSeiran** [comment]
这是我提供的复现用服务端压缩包，顺带一提，启用ssc后放置物块会有明显的一顿一顿的感觉
https://www.123pan.com/s/EcjA-kLyxH.html

**Comment by sgkoishi** [comment]
Try 519f4c1 🤔

**Comment by TskimiSeiran** [comment]
> Try [519f4c1](https://github.com/sgkoishi/yaaiomni/commit/519f4c1e7511406d61e929f28c13735310b88668) 🤔

Not fixed,The Ghost Player BUG,it's still appear when player quit

**Comment by TskimiSeiran** [comment]
> Try [519f4c1](https://github.com/sgkoishi/yaaiomni/commit/519f4c1e7511406d61e929f28c13735310b88668) 🤔

The "Use item and Place block cause Lag" is fixed,But the ghost player when playey quit the server not fixed :(

**Comment by sgkoishi** [comment]
Good to know. For the disconnected players, see #3

**Comment by sgkoishi** [comment]
Probably fixed 1dd1393, can you confirm?

**Comment by TskimiSeiran** [comment]
Yes,it was fixed.
Thanks :)

**Comment by TskimiSeiran** [comment]
> Probably fixed [1dd1393](https://github.com/sgkoishi/yaaiomni/commit/1dd139328c54d26aecd8297fa90a36feaaf0b59e), can you confirm?
Yes,it's fixed.
Thanks :)

**Comment by TskimiSeiran** [comment]
> Probably fixed [1dd1393](https://github.com/sgkoishi/yaaiomni/commit/1dd139328c54d26aecd8297fa90a36feaaf0b59e), can you confirm?

Yes,it's fixed.
Thank you so much :)
