### ISSUE TITLE
Config's AllowJourney How to work?

### ISSUE THREAD

**Issue by TskimiSeiran** [sgkoishi/yaaiomni#5]
I changed this to true,but my journey character still can't join server.
![Screenshot_2023-11-27-18-17-24-66_2665fb67b16260a8d818298cef8dc107](https://github.com/sgkoishi/yaaiomni/assets/115908948/96583c59-7b3b-4c17-8909-1aad5d8ee8fa)

**Comment by sgkoishi** [comment]
Well, `AllowJourney` here is for powers... This is under the section of `Mode: Vanilla`, and it will allow everyone to use journey powers (`tshock.journey.*` permission) just like the vanilla server without TShock.

**Comment by sgkoishi** [comment]
There should be an option `AllowCrossJourney` now which might fit your need.
