### ISSUE TITLE
error when trying to export character

### ISSUE THREAD

**Issue by tungdo0602** [sgkoishi/yaaiomni#6]
![image](https://github.com/sgkoishi/yaaiomni/assets/89498812/83670b85-9a43-4762-bb44-73f5ae2db704)

**Comment by sgkoishi** [comment]
Which version? Should be fixed after v133

**Comment by tungdo0602** [comment]
v138, also the latest commit (v139) doesn't fix it yet.

**Comment by sgkoishi** [comment]
> v138, also the latest commit (v139) doesn't fix it yet.

Can you take a full screenshot including the command you use and the full error message?

**Comment by tungdo0602** [comment]
> > v138, also the latest commit (v139) doesn't fix it yet.
> 
> Can you take a full screenshot including the command you use and the full error message?

![image](https://github.com/sgkoishi/yaaiomni/assets/89498812/788758a7-4dd4-494a-89c7-b78854d4353e)

**Comment by sgkoishi** [comment]
The last line said `Exported` (and it's true). The error message is harmless and removed in b6b4776.
