### ISSUE TITLE
"PrioritizedPacketHandle"不响应热重载，且拦截维度切换服务器。

### ISSUE THREAD

**Issue by Duck15** [sgkoishi/yaaiomni#8]
我在安装了yaaiomni的服务器上尝试配置基于维度的多服务器，当我切换服务器时，玩家连接断开，服务端打印：`Unusual packet 29 detected at state 1 and disconnected. (127.0.0.1:7182)`此处的packet和state不定。
我把配置项中的"PrioritizedPacketHandle"为false，然后reload重试，此时不起作用，切换服务器仍然会被拦截。
但是重启服务器（stop然后再打开）就不拦截了
如果改true然后reload 也是不拦截，同理只有重启生效（（
![image](https://github.com/user-attachments/assets/cc20a58a-7578-43a1-ae23-b9629b5bd698)
![image](https://github.com/user-attachments/assets/805fe751-1a0d-4b23-aa15-8e4dc92a5438)
维度版本：ts qq群内的维度c#版 维度5.9.1 维度6.0.0等均有
yaaiomni版本：
![image](https://github.com/user-attachments/assets/a4815377-8b40-4df5-93c4-fdfcdd90d5e5)
最新版 通过apm更新的~~

**Comment by sgkoishi** [comment]
not everything works with reload, just don't do so.
